### ISSUE TITLE
Fix VT bug "9999999" employees affected

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/WARN#231]
Found this extreme number for a VT data row analysis. This number is too high! Something is wrong with either their data, or our scraping.
I tried to access VT website to check why this might be happening, but the website couldnt be accessed.
Does VT have a new website?

![VT](https://user-images.githubusercontent.com/20691507/138535938-a3c93940-7596-4d0a-be94-a786e59b954c.png)
- [x] Verify & access current VT website
    - [x] Figure out if it's our problem or their problem
    - [ ] Either fix our platform scraper integration, or contact VT about their erroneous data

**Comment by zstumgoren** [comment]
Looks like you're referring to this [record](https://www.vermontjoblink.com/search/warn_lookups/203), which indeed contains the incorrect data at source. The ideal solution would be to contact VT and ask them to correct the record.

If they're unable or unwilling, we should treat this as a task for downstream error in the standardization repo. That way we keep high fidelity to the data and avoid opening the door to lots of edge-case handling in the core scraping framework.

**Comment by ydoc5212** [comment]
Thanks, @zstumgoren! Good thinking, I'll handle it downstream in the standardization repo and will contact VT about getting the record fixed.

**Comment by palewire** [comment]
This is being fixed here, with the value reset as None.

https://github.com/biglocalnews/warn-transformer/pull/60
